buyTech/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
import debug_toolbar

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('djangoapps.home.urls')),
    path('', include('djangoapps.user_account.urls')),
    path('cart/', include('djangoapps.cart.urls')),
    path('order/', include('djangoapps.order.urls')),
    path('product/', include('djangoapps.product.urls')),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += path('__debug__/', include(
                        debug_toolbar.urls)),

djangoapps/cart/urls.py
from . import views
from django.urls import path

urlpatterns = [  
    # cart
    path('', views.cart, name='cart'),
    path('<int:product_id>/add/',
         views.add_to_cart, name='add_to_cart'),
    path('<int:product_id>/update/',
         views.update_cart_item_quantity, name='update_cart_item_quantity'),
]

djangoapps/home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    # customer site pages
    path('', views.home, name='home'),
    path('your-orders/', views.customer_orders, name='your_orders'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    
    # coupon and checkout
    path('coupon/apply/<str:code>/', views.apply_coupon, name='apply_coupon'),
    path('coupon/remove/', views.remove_coupon, name='remove_coupon'),
    path('checkout/', views.checkout, name='checkout'),
    
    # admin site pages
    path('product-admin/', views.product_admin, name='product_admin'),
    path('orders/', views.orders, name='orders'),
]
  

djangoapps/cart/models.py
from django.db import models, transaction
from djangoapps.home.models import CouponUse
from djangoapps.product.models import Product
from djangoapps.user_account.models import CustomUser


#to store cart items 
class Cart(models.Model):
    """
    A Cart model to store cart items, and related functions to manage 
    the cart such as applying or removing coupons, calculating the total cost of 
    the cart, and getting the list of cart items.
    """
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    discount_amount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    coupon_use = models.ForeignKey(
        CouponUse, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}'s Cart"
    
    @property
    def items(self):
        return self.cart_items.select_related('product').all()
    
    @transaction.atomic
    def apply_coupon(self, coupon):
        if coupon:
            coupon_use, created = CouponUse.objects.get_or_create(user=self.user, coupon=coupon)
            if coupon_use.used < coupon.usage_limit:
                try:
                    coupon_use.save()
                    self.coupon_use = coupon_use
                    self.discount_amount = coupon.calculate_discounted_total(self.total)
                    self.save()
                    return True
                except Exception as e:
                    pass
        return False
    
    @transaction.atomic
    def save_coupon_use(self):
        if coupon_use := self.coupon_use:
            coupon_use.used += 1
            coupon_use.save()
        self.coupon_use = None
        self.discount_amount = 0
        self.save()
    
    @transaction.atomic
    def get_cart_total(self):
        self.total = sum(item.get_total for item in self.items)
        if self.coupon_use:
            if self.total > 0:
                self.discount_amount = self.coupon_use.coupon.calculate_discounted_total(self.total)
                
            else:
                self.discount_amount = 0
        else:
            self.discount_amount = self.total
        self.save()
        return self.total
    
    def get_discount(self):
        if self.coupon_use:
            return self.coupon_use.coupon.calculate_coupon_discount(self.total)
        return 0.00
        

# to store the cart items details
class CartItem(models.Model):
    """
    A model to store the details of a product added to a cart.
    """
    cart = models.ForeignKey(
        Cart, on_delete=models.CASCADE, related_name='cart_items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.product.name} x {self.quantity}"
    
    @property
    def get_total(self):
        return self.product.price * self.quantity


# to store the shipping address
class ShippingAddress(models.Model):
    """
    A ShippingAddress model represents a shipping address of an order.
    """
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    user =  models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    name = models.CharField(max_length=60)
    email = models.EmailField('email')
    address_line1 = models.CharField(max_length=60)
    address_line2 = models.CharField(max_length=60)
    pin_code = models.CharField(max_length=6)
    city = models.CharField(max_length=60)
    state = models.CharField(max_length=60)
    country = models.CharField(max_length=60)
    
    def __str__(self):
        return f"Shipping Address of {self.user.username} for order - {self.cart.id}"

djangoapps/home/models.py
from django.db import models
from djangoapps.user_account.models import CustomUser


#to store the contact us details from user
class Contact(models.Model):
    """
    Model for storing contact form details.
    """
    user =  models.ForeignKey(CustomUser,on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=20)
    email = models.EmailField()
    phone = models.CharField(max_length=10)
    msg = models.TextField()
    

# to create coupon
class Coupon(models.Model):
    """
    A model `Coupon` used to store coupon details such as code, discount, and 
    usage_limit. 
    """

    DISCOUNT_TYPES = (
        ('Percentage', 'Percentage'),
        ('Fixed', 'Fixed Amount'),
    )

    code = models.CharField(max_length=50, unique=True)
    discount_type = models.CharField(max_length=20, choices=DISCOUNT_TYPES, default=DISCOUNT_TYPES[1])
    discount = models.DecimalField(max_digits=10, decimal_places=2, default=0.00)
    usage_limit = models.PositiveIntegerField(blank=True, default=1)

    def __str__(self):
        return self.code
    
    def calculate_discounted_total(self, total):
        if self.discount_type == 'Percentage':
            return (total-((self.discount / 100) * total))
        else:
            return (total-self.discount)
        
    def calculate_coupon_discount(self,total):
        if self.discount_type == 'Percentage':
            return ((self.discount / 100) * total)
        else:
            return (self.discount)
        
    

#to track the coupon usage for each user
class CouponUse(models.Model):
    """
    A model to track the usage of coupons for each user. It has fields to store the 
    user ID, coupon ID, and the number of times the coupon has been used. It also has 
    a unique constraint to ensure that a user can only use a coupon once
    """

    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    coupon = models.ForeignKey(Coupon, on_delete=models.CASCADE)
    used = models.PositiveIntegerField(default=0)
    class Meta:
        unique_together = ('user', 'coupon')
        



    
    

djangoapps/cart/forms.py
# To create user checkout detail form
from .models import ShippingAddress
from django import forms


class ShippingAddressForm(forms.ModelForm):
    name = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Name'}))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}
    ))
    address_line1 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Address Line 1'}
    ))
    address_line2 = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Address Line 2'}
    ))
    pin_code = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Pin Code'}
    ))
    city = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'City/Town'}))
    state = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'State'}))
    country = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Country'}))
    
    class Meta:
        model = ShippingAddress
        fields = [
            'name', 'email', 'address_line1', 'address_line2',
            'pin_code', 'city', 'state', 'country'
        ]

djangoapps/cart/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, redirect, render
from .models import Cart, CartItem
from djangoapps.home.forms import CouponForm
from djangoapps.home.models import Coupon
from djangoapps.product.models import Product
from django.db import transaction

# cart view
@login_required
def cart(request):
    cart, created = Cart.objects.get_or_create(user=request.user)
    cart.total = cart.get_cart_total()
    items = CartItem.objects.filter(cart=cart).select_related('product')
    coupons = Coupon.objects.all()
    coupon_form = CouponForm()
    coupon_discount = cart.get_discount()
    
    return render(request, "customer/cart.html", {
        "cart_items": items,
        "cart": cart,
        "coupons": coupons,
        "coupon_form": coupon_form,
        "coupon_discount": coupon_discount,
        "total_items": len(items),
    })


# adding products to cart
@login_required
def add_to_cart(request, product_id):
    cart, created = Cart.objects.get_or_create(user=request.user)
    product = Product.objects.filter(pk=product_id).first()
    if product.in_stock:
        with transaction.atomic():
            item, created = CartItem.objects.get_or_create(cart=cart, product=product)
            if not created:
                item.quantity += 1
                item.save()
            product.stock -= 1
            product.save()
            cart.total = cart.get_cart_total()
    else:
        messages.error(request, "This product is out of stock.")
        return redirect("home")
    
    messages.success(request, "Added to cart.")
    return redirect("cart")


# update cart-item
@login_required
def update_cart_item_quantity(request, product_id):
    if request.method == "POST":
        cart = get_object_or_404(Cart, user=request.user)
        product = get_object_or_404(Product, pk=product_id)
        cart_item = get_object_or_404(CartItem, cart=cart, product=product)
        new_quantity = int(request.POST.get("quantity"))

        cart_item.quantity += new_quantity
        if request.POST.get("remove") == "true" or cart_item.quantity == 0:
            with transaction.atomic():
                if cart_item.quantity == 0:
                    product.stock -= new_quantity
                else:
                    product.stock += cart_item.quantity
                cart_item.delete()
                product.save()
            return JsonResponse(
                {
                    "success": True,
                    "remove": True,
                    "total": cart.get_cart_total(),
                    "coupon_discount": cart.get_discount(),
                    "discount_amount": cart.discount_amount,
                }
            )

        if (new_quantity > 0 and product.in_stock) or (new_quantity <= 0):
            with transaction.atomic():
                product.stock -= new_quantity
                product.save()
                cart_item.save()
            return JsonResponse(
                {
                    "success": True,
                    "quantity": cart_item.quantity,
                    "total": cart.get_cart_total(),
                    "coupon_discount": cart.get_discount(),
                    "discount_amount": cart.discount_amount,
                    "remove": False,
                }
            )
    return JsonResponse({"success": False, "message": "This product is out of stock."})

djangoapps/home/views.py
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render
from djangoapps.cart.forms import ShippingAddressForm
from djangoapps.cart.models import Cart, ShippingAddress
from djangoapps.order.models import Order, OrderItem
from djangoapps.product.models import Product

from .decorators import admin_login_required
from .forms import CouponForm
from .models import Contact, Coupon

""" customer site views """
# home page
def home(request):
    return render(request, "customer/home.html")


# order history of user
@login_required
def customer_orders(request):
    orders = Order.objects.filter(user=request.user).order_by("-created_at")
    return render(request, "customer/your_orders.html", context={"orders": orders})


# about page
def about(request):
    return render(request, "customer/about.html")


# contact page
def contact(request):
    if request.method == "POST":
        name = request.POST["name"]
        email = request.POST["email"]
        phone = request.POST["phone"]
        msg = request.POST["msg"]
        contact = Contact.objects.create(name=name, email=email, phone=phone, msg=msg)
        if request.user.is_authenticated:
            contact.user = request.user
            contact.save()
    return render(request, "customer/contact.html")


# to apply coupon
@login_required
def apply_coupon(request, code):
    cart = get_object_or_404(Cart, user=request.user) or Cart.objects.create(
        user=request.user
    )
    coupon_form = CouponForm(request.POST)
    if coupon_form.is_valid():
        code = coupon_form.cleaned_data["code"]
    if code:
        try:
            coupon = get_object_or_404(Coupon, code=code)
        except Coupon.DoesNotExist:
            messages.error(request, "Invalid coupon code.")
            return JsonResponse({"success": False, "message": "Invalid coupon code."})
        # import pdb; pdb.set_trace()
        if cart.apply_coupon(coupon):
            return JsonResponse(
                {
                    "success": True,
                    "message": "Coupon applied.",
                    "total": cart.get_cart_total(),
                    "coupon_discount": cart.get_discount(),
                    "discount_amount": cart.discount_amount,
                }
            )
        else:
            return JsonResponse({"success": False, "message": "Invalid coupon code."})

    return JsonResponse({"success": False, "message": "Invalid coupon form data."})


# to remove coupon
@login_required
def remove_coupon(request):
    if request.method != "POST":
        return JsonResponse({"messages": "Invalid request method"}, status=400)
    cart_id = request.POST.get("cart_id")
    cart = get_object_or_404(Cart, pk=cart_id)
    if cart.coupon_use:
        cart.coupon_use.used -= 1
        cart.coupon_use = None
    cart.save()
    response_data = {
        "total": cart.get_cart_total(),
        "coupon_discount": cart.get_discount(),
        "discount_amount": cart.discount_amount,
        "message": "Coupon removed successfully.",
    }
    return JsonResponse(response_data)


# cart checkout
@login_required
def checkout(request):
    cart = get_object_or_404(Cart, user=request.user)
    shipping_address = ShippingAddress.objects.filter(
        cart=cart, user=request.user
    ).first()
    if request.method == "POST":
        form = ShippingAddressForm(request.POST, instance=shipping_address)
        if form.is_valid():
            shipping_address = form.save(commit=False)
            shipping_address.user = request.user
            shipping_address.cart = cart
            shipping_address.save()
            form = ShippingAddressForm(instance=shipping_address)
    else:
        form = ShippingAddressForm()
    cart_items = cart.items()
    return render(
        request,
        "customer/checkout.html",
        context={
            "cart": cart,
            "form": form,
            "cart_items": cart_items,
            "shipping_address": shipping_address,
            'paypal_client_id': settings.PAYPAL_CLIENT_ID,
        },
    )



""" product admin site """
# dashboard for admin
@admin_login_required
def product_admin(request):
    product_admin = request.user
    products = Product.get_products_by_admin(product_admin=product_admin)
    return render(request, "admin/product_admin.html", context={"products": products})


# to display the orders
@admin_login_required
def orders(request):
    placed_orders = []
    # Retrieve orders that belong to the admin's products
    orders = Order.objects.all().order_by("-created_at")
    # Iterate through the orders and retrieve order items for admin's products
    for order in orders:
        order_items = OrderItem.objects.filter(
            order=order, product__product_admin=request.user
        )
        if order_items.exists():
            placed_orders.append(order)
            continue
    context = {"orders": placed_orders}
    return render(request, "admin/orders.html", context)

templates/customer/checkout.html
{% extends 'customer/base.html' %}
{%load static%}
{%block title%} CheckOut {%endblock title%}

{%block body%}
<h2 class="text-center my-3"> Checkout </h2>
<div class="row  justify-content-center mx-0">
    <div class="col-5">
        <div id="shipping-address">
            <h3>Shipping Address</h3>
            <div id="shipping-details">
                {% if shipping_address %}
                <p>Name: {{ shipping_address.name }}</p>
                <p>Email: {{ shipping_address.email }}</p>
                <p>Address: {{ shipping_address.address_line1 }}, {{ shipping_address.address_line2 }},
                    {{shipping_address.city }}, {{ shipping_address.state }}, {{ shipping_address.pin_code }}</p>
                {% endif %}
            </div>
            <form method="POST" enctype="multipart/form-data" id="form-address">
                {% csrf_token %}
                <div id="shipping-address-form" {% if shipping_address %} style="display: none;" {% endif %}>
                    {% with form=form %}
                    {% include 'customer/shipping_address_form.html' %}
                    {% endwith %}
                </div>
                <div id="shipping-address-error"></div>
                <button type="button" class="btn btn-dark my-2" id="save-address">
                    {% if shipping_address %} Edit {% else %} Save {% endif %}
                </button>
            </form>
            <div id="shipping-address-error" ></div>
        </div>
    </div>
    <div class="col-5">
            <div class="order-summary mb-4">
                <div class="card" style="height: auto;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col">
                                <div class="d-flex justify-content-between align-items-center mb-2">
                                    <div>
                                        <h5 class="mb-1">Order Summary</h5>
                                        <p class="mb-0 pb-0">You have {{cart_items|length}} items in your orders</p>
                                    </div>
                                    <div>
                                        <a class="text-decoration-none text-body" href="/cart/">Edit <i class="fas fa-pen"></i> </a>
                                    </div>
                                </div>
                                {%for item in cart_items %}
                                <div class="card mb-2">
                                    <div class="card-body px-2 py-1">
                                        <div class="d-flex justify-content-between">
                                            <div class="d-flex flex-row align-items-center">
                                                <div>
                                                    <img src="{{ item.product.image.url}}" class="img-fluid rounded-3"
                                                        alt="Shopping item" style="width: 40px;">
                                                </div>
                                                <div class="ms-2">
                                                    <p class="my-0">{{item.product.name}}</p>
                                                </div>
                                            </div>
                                            <div class="d-flex flex-row align-items-center">
                                                <div class="ms-2">
                                                    <p class="my-0">Price: ${{item.product.price}}</p>
                                                    <p class="my-0">Qty: {{item.quantity}}</p>
                                                </div>
                                            </div>
                                    
                                        </div>
                                    </div>
                                </div>
                                {%endfor%}
                                {%if cart.total > 0 %}
                                <hr class="my-2">
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">Total MRP</p>
                                    <p class="mb-2">${{cart.total}}</p>
                                </div>
                                
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">Coupon Discount </p>
                                    <p class="mb-2"> - ${%if cart.coupon_use %} {{cart.coupon_use.coupon.discount}} {%else%} {{0.00}} {%endif%}</p>
                                </div>
                                <hr class="my-2">
                                <div class="d-flex justify-content-between">
                                    <p class="mb-2">Total Amount </p>
                                    <p class="mb-2">${{cart.discount_amount}}</p>
                                </div>
                                {%endif%}
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
            <div id="paypal-button-container"></div>
    </div>
</div>
</div>

<script src="https://www.paypal.com/sdk/js?client-id={{paypal_client_id}}&currency=USD"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    function initPayPalButton() {
        $('#shipping-address-error').empty();
        
        paypal.Buttons({
            style: {
                shape: 'rect',
                color: 'black',
                layout: 'vertical',
                label: 'paypal',
            },

            createOrder: function (data, actions) {
                var isFormFilled = $('#shipping-details').is(':visible');
                if (isFormFilled) {
                    return actions.order.create({
                        purchase_units: [{ "amount": { "currency_code": "USD", "value": '{{cart.discount_amount}}' } }],
                        application_context: {
                            shipping_preference: 'NO_SHIPPING'
                        },
                    });
                }
                else{
                    $('#shipping-address-error').html('<p style="color:red;">Please save the address.<p>');
                    return false;
                }
                
            },
            onApprove: function (data, actions) {
                return actions.order.capture().then(function (orderData) {
                    
                    $.ajax({
                        type: 'POST',
                        url: '/order/create/',  
                        data: {
                            cart_id: '{{cart.id}}',
                            billing_address: null,
                        },
                        headers: {
                            'X-CSRFToken': $('input[name=csrfmiddlewaretoken]').val()
                        },
                        success: function (response) {
                            if (response.success) {
                                window.location.href = '/your-orders/';
                                console.log('Order placed');
                            } else {
                                console.log('Failed to update order status.',message);
                            }
                        },
                        error: function () {
                            console.log('An error occurred while updating order status.');
                        }
                    });
                });
            },
            onError: function (err) {
                var isFormFilled = $('#shipping-details').is(':visible');
                if(!isFormFilled){
                    $('#shipping-address-error').html('<p style="color:red;">Please save the address.<p>');
                }
                else{
                    $('#shipping-address-error').html('<p style="color:red;">Payment Failed. Please try again!<p>');
                }
            },
            onCancel: function (data) {
                $('#shipping-address-error').html('<p style="color:red;">Payment canceled. Please try again!<p>');
            }


        }).render('#paypal-button-container');
        }
    initPayPalButton();
</script>

<script>
    $(document).ready(function () {
       
        function getAddressDataFromPinCode(pinCode) {
            var apiUrl = 'https://api.zippopotam.us/in/' + pinCode;

            $.ajax({
                url: apiUrl,
                type: 'GET',
                success: function (data) {
                    if (data && data.places && data.places[0]) {
                        var place = data.places[0];
                        $('#id_state').val(place['state']);
                        $('#id_country').val(data['country']);
                    }
                },
                error: function (error) {
                    console.log('Error fetching address data:', error);
                }
            });
        }

        $('#id_pin_code').on('input', function () {
            var pinCode = $(this).val();
            getAddressDataFromPinCode(pinCode);
        });
        
        // Client side validations
        $('#form-address input').on('blur', function () {
            $('.error-message').empty();
            return validateField($(this));
        });

        // To validate email format
        function isValidEmail(email) {
            var emailPattern = /^[a-zA-Z0-9._-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}$/;
            return emailPattern.test(email);
        }

        // To validate pin code format
        function isValidPinCode(pinCode) {
            var pinCodePattern = /^\d{6}$/;
            return pinCodePattern.test(pinCode);
        }

        function validateField(input){

                var id = input.attr('id');
                if (input.val() === '') {
                    $('#' + id + '_error').html('<small style="color: red">This field is required!</small>');
                    return false;
                }
                if (input.attr('type') === 'email' && !isValidEmail(input.val())) {
                    $('#' + id + '_error').html('<small style="color: red">Enter a valid email address</small>');
                    return false;
                }
                if (input.attr('name') === 'pin_code' && !isValidPinCode(input.val())) {
                    $('#' + id + '_error').html('<small style="color: red">Enter a valid pin code</small>');
                    isValid = false;
                }
                return true;
        }

        $('#save-address').click(function ()  {
            if ($('#shipping-address-form').is(':visible')) {
                $('#form-address').submit();
            } else {
                $('#shipping-details').toggle();
                $('#shipping-address-form').toggle();
                $(this).text(function (i, text) {
                    return text === 'Edit' ? 'Save' : 'Edit';
                });
            }
            if ($saveEditButton.text() === 'Edit') {
                $shippingAddressForm.show();
                $shippingDetails.hide();
                $saveEditButton.text('Save');
            } else {
                $shippingAddressForm.hide();
                $shippingDetails.show();
                $saveEditButton.text('Edit');
            }
            
            $('.error-message').empty(); 
            var isValid = true; 
            $('#form-address input').each(function () {
                if (!validateField($(this))) {
                    isValid = false;
                    return false;
                }
                isValid=true;
            });

            if (isValid) {
                $('#form-address').submit(); 
            }
        });
    });
   
</script>

{%endblock body%}

templates/customer/contact.html
{% extends "customer/base.html" %}
{%load static%}
{%block title%}Contact Us {%endblock title%}
{%block contactactive%} active {%endblock contactactive%}
{%block body%}
<div class="container my-3">
  <h2 class="text-center"> Contact Us </h2>
  <form class="row g-4 my-3 d-flex justify-content-center" action="/contact/"
    method="POST">
    {% csrf_token %}
    <div class="col-8">
      <label for="name" class="form-label">Name</label>
      <input type="text" class="form-control" id="name" name="name" />
    </div>
    <div class="col-8">
      <label for="email" class="form-label">Email</label>
      <input type="email" class="form-control" id="email" name="email" />
    </div>
    <div class="col-8">
      <label for="phone" class="form-label">Contact Number</label>
      <input type="phone" class="form-control" id="phone" name="phone" />
    </div>
    <div class="col-8">
      <label for="msg" class="form-label">Message</label>
      <textarea class="form-control" id="msg" row="5" name="msg"></textarea>
    </div>
    <div class="col-8">
      <button type="submit" class="btn btn-dark">Submit</button>
    </div>
  </form>
</div>
{%endblock body%}